import { db } from './database.js';

interface RawEventRow {
  festaTipo?: 'DEBUTANTE' | 'CASAMENTO' | 'INFANTIL' | 'ANIVERSARIO' | 'CORPORATIVO' | 'OUTRO';
  clienteNome: string;
  clienteDoc?: string;
  clienteTel?: string;
  clienteEmail?: string;
  clienteEnd?: string;
  atracao: string;
  efeitos?: string;
  data: string; // YYYY-MM-DD
  horario: string;
  horarioTermino?: string;
  duracao?: number;
  local: string;
  cidade?: string;
  estado?: string;
  concluida: boolean;
  cancelado?: boolean;
  parceria?: string;
  valorCobrado: number;
  valorPago?: number;
  valorAPagar?: number;
  pagoStatus?: 'SIM' | 'NAO' | 'PARCIAL';
  observacoes?: string;
}

export const SHEET_EVENTS_DATA: RawEventRow[] = [
  // ==========================================
  // TABELA 1: EVENTOS SOCIAIS / FESTAS (IMAGEM 2)
  // ==========================================
  {
    festaTipo: 'DEBUTANTE',
    clienteNome: 'Camila Rodrigues',
    clienteDoc: '111.222.333-01',
    clienteTel: '(11) 98765-1000',
    clienteEmail: 'ricardo.ametller@demoeventos.com',
    clienteEnd: 'São Paulo - SP',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro CO2',
    data: '2025-10-25',
    horario: '23:30',
    horarioTermino: '00:30',
    duracao: 1,
    local: 'Escudez eventos',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    valorAPagar: 0,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'OUTRO',
    clienteNome: 'Lucas Mendonca',
    clienteDoc: '111.222.333-02',
    clienteTel: '(11) 98765-1001',
    clienteEmail: 'erick.amorim@demoeventos.com',
    clienteEnd: 'Rua Vereador Rubens de Oliveira, 260 - Diadema',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro CO2',
    data: '2025-10-25',
    horario: '19:20',
    horarioTermino: '20:20',
    duracao: 1,
    local: 'Rua Vereador Rubens de Oliveira, 260 - Diadema',
    cidade: 'Diadema',
    estado: 'SP',
    concluida: true,
    valorCobrado: 650,
    valorPago: 650,
    valorAPagar: 0,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'OUTRO',
    clienteNome: 'Camila Rodrigues',
    clienteDoc: '111.222.333-03',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro CO2',
    data: '2025-10-12',
    horario: '16:00',
    horarioTermino: '17:00',
    duracao: 1,
    local: 'Av presidente café filho 1691',
    cidade: 'São Bernardo do Campo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    valorAPagar: 0,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'INFANTIL',
    clienteNome: 'Camila Rodrigues',
    clienteDoc: '111.222.333-04',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro CO2',
    data: '2025-10-11',
    horario: '19:00',
    horarioTermino: '20:00',
    duracao: 1,
    local: 'Rua Bandeirantes, nº239',
    cidade: 'São Caetano do Sul',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    valorAPagar: 0,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'INFANTIL',
    clienteNome: 'Camila Rodrigues',
    clienteDoc: '111.222.333-05',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro CO2',
    data: '2025-12-19',
    horario: '21:30',
    horarioTermino: '22:30',
    duracao: 1,
    local: 'Av. Brasília, 363 - Vila Bela Vista, Santo André - SP',
    cidade: 'Santo André',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    valorAPagar: 0,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'ANIVERSARIO',
    clienteNome: 'Beatriz Alcantara',
    clienteDoc: '111.222.333-06',
    clienteTel: '(11) 98765-1002',
    clienteEnd: 'Rua José Bonifácio, 360 - Centro - São Bernardo do Campo',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro CO2',
    data: '2026-03-28',
    horario: '23:00',
    horarioTermino: '00:00',
    duracao: 1,
    local: 'Rua José Bonifácio, 360 - Centro - São Bernardo do Campo',
    cidade: 'São Bernardo do Campo',
    estado: 'SP',
    concluida: true,
    valorCobrado: 600,
    valorPago: 600,
    valorAPagar: 0,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'DEBUTANTE',
    clienteNome: 'Rodrigo Farias',
    clienteDoc: '111.222.333-07',
    clienteTel: '(11) 98765-1003',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro CO2',
    data: '2026-01-17',
    horario: '00:30',
    horarioTermino: '01:30',
    duracao: 1,
    local: 'Rua Henrique Husse - Chácara Recanto Tropical',
    cidade: 'Ribeirão Pires',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    valorAPagar: 0,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'DEBUTANTE',
    clienteNome: 'Juliana Vasconcelos',
    clienteDoc: '111.222.333-08',
    clienteTel: '(11) 98765-1004',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro CO2',
    data: '2026-02-07',
    horario: '23:00',
    horarioTermino: '00:00',
    duracao: 1,
    local: 'Av Rio das Pedras 186 - Jardim Aricanduva',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: true,
    valorCobrado: 600,
    valorPago: 600,
    valorAPagar: 0,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'INFANTIL',
    clienteNome: 'Rodrigo Farias',
    clienteDoc: '111.222.333-09',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro CO2',
    data: '2026-03-14',
    horario: '21:00',
    horarioTermino: '22:00',
    duracao: 1,
    local: 'Bambolê Espaço Kids - Av Vereador Abel Ferreira 325 - Jd Anália Franco',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    valorAPagar: 0,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'DEBUTANTE',
    clienteNome: 'Marcelo Antunes',
    clienteDoc: '111.222.333-10',
    clienteTel: '(11) 98765-1005',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro CO2',
    data: '2026-03-27',
    horario: '00:15',
    horarioTermino: '01:15',
    duracao: 1,
    local: 'Av Newton M. De Andrade, 405 - São Bernardo do Campo',
    cidade: 'São Bernardo do Campo',
    estado: 'SP',
    concluida: true,
    valorCobrado: 600,
    valorPago: 600,
    valorAPagar: 0,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CASAMENTO',
    clienteNome: 'Fernanda Lima',
    clienteDoc: '111.222.333-11',
    clienteTel: '(11) 98765-1006',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro CO2',
    data: '2026-04-21',
    horario: '17:00',
    horarioTermino: '18:30',
    duracao: 1.5,
    local: 'Av. Nova Cantareira, 4235 - Tucuruvi, São Paulo - SP (Mansão Capricho)',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: true,
    valorCobrado: 800,
    valorPago: 800,
    valorAPagar: 0,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CASAMENTO',
    clienteNome: 'Gabriel Siqueira',
    clienteDoc: '111.222.333-12',
    clienteTel: '(11) 98765-1007',
    atracao: 'Robo Nextrom e 2 La Casa de Papel',
    efeitos: 'Cilindro e gerb',
    data: '2026-04-18',
    horario: '22:00',
    horarioTermino: '23:00',
    duracao: 1,
    local: 'Estr. dos Vazez, Cambuí - MG, 37600-000',
    cidade: 'Cambuí',
    estado: 'MG',
    concluida: true,
    valorCobrado: 1400,
    valorPago: 1400,
    valorAPagar: 0,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'DEBUTANTE',
    clienteNome: 'Larissa Manoela',
    clienteDoc: '111.222.333-13',
    clienteTel: '(11) 98765-1008',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro CO2',
    data: '2026-05-16',
    horario: '21:00',
    horarioTermino: '22:00',
    duracao: 1,
    local: 'Av. Cap. Mário Toledo de Camargo 5561 - Jardim Irene, Santo André - SP',
    cidade: 'Santo André',
    estado: 'SP',
    concluida: true,
    valorCobrado: 400,
    valorPago: 400,
    valorAPagar: 0,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'INFANTIL',
    clienteNome: 'Thiago Meireles',
    clienteDoc: '111.222.333-14',
    clienteTel: '(11) 98765-1009',
    atracao: 'Robo Nextrom e 2 La Casa de Papel',
    efeitos: 'Cilindro e gerb',
    data: '2026-05-17',
    horario: '22:00',
    horarioTermino: '23:00',
    duracao: 1,
    local: 'Av Doutor Renato de Andrade Maia - Jardim Maia 278, Guarulhos - SP',
    cidade: 'Guarulhos',
    estado: 'SP',
    concluida: true,
    valorCobrado: 800,
    valorPago: 800,
    valorAPagar: 0,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'DEBUTANTE',
    clienteNome: 'Mariana Prado',
    clienteDoc: '111.222.333-15',
    clienteTel: '(11) 98765-1010',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro CO2',
    data: '2026-08-15',
    horario: '23:00',
    horarioTermino: '00:00',
    duracao: 1,
    local: 'Av Rio das Pedras 186 - Jardim Aricanduva',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: true,
    valorCobrado: 550,
    valorPago: 550,
    valorAPagar: 0,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'DEBUTANTE',
    clienteNome: 'Carlos Eduardo Silva',
    clienteDoc: '111.222.333-16',
    clienteTel: '(11) 98765-1011',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-09-19',
    horario: '22:00',
    horarioTermino: '23:00',
    duracao: 1,
    local: 'Avenida Raimundo Pereira de Magalhães 6275',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: false,
    valorCobrado: 600,
    valorPago: 0,
    valorAPagar: 600,
    pagoStatus: 'NAO',
  },
  {
    festaTipo: 'DEBUTANTE',
    clienteNome: 'Rafaela Santos',
    clienteDoc: '111.222.333-17',
    clienteTel: '(11) 98765-1012',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-10-10',
    horario: '21:00',
    horarioTermino: '22:00',
    duracao: 1,
    local: 'Estrada do Yamane 1093',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: false,
    valorCobrado: 600,
    valorPago: 200,
    valorAPagar: 400,
    pagoStatus: 'PARCIAL',
  },
  {
    festaTipo: 'DEBUTANTE',
    clienteNome: 'Diego Hypolito',
    clienteDoc: '111.222.333-18',
    clienteTel: '(11) 98765-1013',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2027-04-03',
    horario: '23:00',
    horarioTermino: '00:00',
    duracao: 1,
    local: 'Buffet Carol Eventos',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: false,
    valorCobrado: 600,
    valorPago: 0,
    valorAPagar: 600,
    pagoStatus: 'NAO',
  },
  {
    festaTipo: 'DEBUTANTE',
    clienteNome: 'Patricia Abravanel',
    clienteDoc: '111.222.333-19',
    clienteTel: '(11) 98765-1014',
    atracao: 'Robo Nextrom e 2 La Casa de Papel',
    efeitos: 'Cilindro e gerb',
    data: '2027-04-15',
    horario: '23:00',
    horarioTermino: '00:00',
    duracao: 1,
    local: 'Espaço Aricanduva',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: false,
    valorCobrado: 1000,
    valorPago: 400,
    valorAPagar: 600,
    pagoStatus: 'PARCIAL',
  },

  // ==========================================
  // TABELA 2: PROGRAMAÇÃO BURGER KING & PARCERIAS (IMAGEM 1)
  // ==========================================
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-20',
    clienteTel: '(11) 98765-1015',
    clienteEmail: 'felipe.rossi@demoeventos.com',
    clienteEnd: 'Minas Gerais',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-05-20',
    horario: '16:00',
    horarioTermino: '17:00',
    duracao: 1,
    local: 'BKN, Shopping Gran Plaza',
    cidade: 'Santo André',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-21',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-05-21',
    horario: '11:00',
    horarioTermino: '12:00',
    duracao: 1,
    local: 'BKN Rodovia Anchieta',
    cidade: 'São Bernardo do Campo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 550,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-22',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro CO2',
    data: '2026-05-22',
    horario: '11:00',
    horarioTermino: '12:00',
    duracao: 1,
    local: 'BKN - 18823 - BURGER KING ILS SHOP METRO TATUAPE II',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 550,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-23',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro CO2',
    data: '2026-05-23',
    horario: '11:00',
    horarioTermino: '12:00',
    duracao: 1,
    local: 'BKN - 20626 - BURGER KING CARREFOUR DIADEMA',
    cidade: 'Diadema',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 550,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-24',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro CO2',
    data: '2026-05-23',
    horario: '15:00',
    horarioTermino: '16:00',
    duracao: 1,
    local: 'BKN - 20526 - BURGER KING MAUA PLAZA SHOP II',
    cidade: 'Mauá',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 550,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-25',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-05-28',
    horario: '14:00',
    horarioTermino: '15:00',
    duracao: 1,
    local: '26404 - BURGER KING FS GRU - APENAS CUSTO DA IDA AO LOCAL',
    cidade: 'Guarulhos',
    estado: 'SP',
    concluida: true,
    cancelado: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 100,
    valorPago: 100,
    pagoStatus: 'SIM',
    observacoes: 'Cancelado pelo cliente - cobrado apenas custo da ida ao local',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-26',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-06-03',
    horario: '11:00',
    horarioTermino: '12:00',
    duracao: 1,
    local: 'BKN - 15906 - BURGER KING PARQUE DOM PEDRO SHOP',
    cidade: 'Campinas',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 720,
    valorPago: 720,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-27',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-06-05',
    horario: '16:00',
    horarioTermino: '17:00',
    duracao: 1,
    local: '16173 - BURGER KING SHOP INTERLAGOS',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-28',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-06-05',
    horario: '11:00',
    horarioTermino: '12:00',
    duracao: 1,
    local: 'BKN - 28811 - BURGER KING FS SP - AV RAGUEB',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-29',
    atracao: 'Robo Nextrom e 1 La Casa de Papel',
    efeitos: 'Cilindro e gerb',
    data: '2026-06-08',
    horario: '14:00',
    horarioTermino: '15:00',
    duracao: 1,
    local: 'BKN SANTO ANDRÉ AV ESTADOS',
    cidade: 'Santo André',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 550,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-30',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-06-08',
    horario: '18:00',
    horarioTermino: '19:00',
    duracao: 1,
    local: 'BKN SANTO ANDRÉ DOM PEDRO',
    cidade: 'Santo André',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 550,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-31',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-06-09',
    horario: '17:00',
    horarioTermino: '18:00',
    duracao: 1,
    local: 'BKN JACU PESSEGO',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 550,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-32',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-06-18',
    horario: '13:00',
    horarioTermino: '14:00',
    duracao: 1,
    local: 'BKN EXTRA ANCHIETA',
    cidade: 'São Bernardo do Campo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-33',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro CO2',
    data: '2026-06-25',
    horario: '11:00',
    horarioTermino: '12:00',
    duracao: 1,
    local: 'BKN PRESTES MAIA SBC',
    cidade: 'São Bernardo do Campo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 550,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-34',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-06-29',
    horario: '10:00',
    horarioTermino: '11:00',
    duracao: 1,
    local: 'BURGER KING ILR SANTO ANDRE - R CEL OLIVEIRA LIMA',
    cidade: 'Santo André',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-35',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-06-30',
    horario: '11:00',
    horarioTermino: '12:00',
    duracao: 1,
    local: 'BURGER KING SHOP ABC',
    cidade: 'Santo André',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-36',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-06-30',
    horario: '18:00',
    horarioTermino: '23:00',
    duracao: 5,
    local: 'BURGER KING FS SP AV - 5 horas de evento (causa: atraso)',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 2500,
    valorPago: 2500,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-37',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-07-03',
    horario: '16:00',
    horarioTermino: '17:00',
    duracao: 1,
    local: 'BK SHOP ATRIUM',
    cidade: 'Santo André',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-38',
    atracao: 'Robo Nextrom',
    efeitos: 'Gerb',
    data: '2026-07-03',
    horario: '16:00',
    horarioTermino: '17:00',
    duracao: 1,
    local: 'BK FS ARICANDUVA',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 550,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-39',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-07-10',
    horario: '14:00',
    horarioTermino: '15:00',
    duracao: 1,
    local: 'BK CARREFOUR VERGUEIRO',
    cidade: 'São Bernardo do Campo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-40',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-07-10',
    horario: '17:00',
    horarioTermino: '18:00',
    duracao: 1,
    local: 'BK CENTRAL PLAZA',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-41',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-07-27',
    horario: '15:00',
    horarioTermino: '16:00',
    duracao: 1,
    local: 'BK MAUA PLAZA SHOPPING 1',
    cidade: 'Mauá',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-42',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-07-30',
    horario: '16:00',
    horarioTermino: '17:00',
    duracao: 1,
    local: 'BK SHOP DIADEMA',
    cidade: 'Diadema',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-43',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-07-31',
    horario: '15:00',
    horarioTermino: '16:00',
    duracao: 1,
    local: 'BK CARREFOUR ST ANDRE',
    cidade: 'Santo André',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-44',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-08-05',
    horario: '15:00',
    horarioTermino: '16:00',
    duracao: 1,
    local: 'BK SHOP ABC',
    cidade: 'Santo André',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-45',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-08-07',
    horario: '16:00',
    horarioTermino: '17:00',
    duracao: 1,
    local: 'BK PLAZA SUL',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-46',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-08-08',
    horario: '16:00',
    horarioTermino: '17:00',
    duracao: 1,
    local: 'BK CENTER PENHA',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 500,
    valorPago: 500,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-47',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-08-20',
    horario: '10:00',
    horarioTermino: '11:00',
    duracao: 1,
    local: 'BK CAMPINAS 2',
    cidade: 'Campinas',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 750,
    valorPago: 750,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Giovanna Antonelli',
    clienteDoc: '111.222.333-48',
    clienteTel: '(11) 98765-1016',
    clienteEnd: 'Osasco - SP',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-06-10',
    horario: '16:00',
    horarioTermino: '17:00',
    duracao: 1,
    local: 'BK RUA XV NOVEMBRO CENTRO SP',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 0,
    pagoStatus: 'NAO',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Giovanna Antonelli',
    clienteDoc: '111.222.333-49',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-07-01',
    horario: '12:00',
    horarioTermino: '13:00',
    duracao: 1,
    local: 'BK PG MAL MALLET',
    cidade: 'Praia Grande',
    estado: 'SP',
    concluida: false,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 0,
    pagoStatus: 'NAO',
    observacoes: 'Data a confirmar',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Giovanna Antonelli',
    clienteDoc: '111.222.333-50',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro CO2',
    data: '2026-07-24',
    horario: '12:00',
    horarioTermino: '13:00',
    duracao: 1,
    local: 'BK BOQUEIRAO SANTOS LITORAL',
    cidade: 'Santos',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 550,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Giovanna Antonelli',
    clienteDoc: '111.222.333-51',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-08-16',
    horario: '12:00',
    horarioTermino: '14:00',
    duracao: 2,
    local: 'BK PAULISTA',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 1000,
    valorPago: 1000,
    pagoStatus: 'SIM',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Giovanna Antonelli',
    clienteDoc: '111.222.333-52',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-08-10',
    horario: '16:00',
    horarioTermino: '17:00',
    duracao: 1,
    local: 'BK GUARUJA ADEMAR BARROS',
    cidade: 'Guarujá',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 0,
    pagoStatus: 'NAO',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-53',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-08-26',
    horario: '14:00',
    horarioTermino: '15:00',
    duracao: 1,
    local: 'BK SAO CARLOS',
    cidade: 'São Carlos',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 1100,
    valorPago: 0,
    pagoStatus: 'NAO',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Giovanna Antonelli',
    clienteDoc: '111.222.333-54',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-08-10',
    horario: '16:00',
    horarioTermino: '17:00',
    duracao: 1,
    local: 'BK CARAPICUIBA',
    cidade: 'Carapicuíba',
    estado: 'SP',
    concluida: false,
    parceria: 'Buffet Parceiro',
    valorCobrado: 600,
    valorPago: 0,
    pagoStatus: 'NAO',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Giovanna Antonelli',
    clienteDoc: '111.222.333-55',
    atracao: 'Robo Nextrom',
    efeitos: 'N',
    data: '2026-06-10',
    horario: '11:00',
    horarioTermino: '12:00',
    duracao: 1,
    local: 'BK METRO SAO BENTO CENTRO SP',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 0,
    pagoStatus: 'NAO',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Giovanna Antonelli',
    clienteDoc: '111.222.333-56',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-09-10',
    horario: '14:00',
    horarioTermino: '15:00',
    duracao: 1,
    local: 'BK SAO VICENTE PRES WILSON',
    cidade: 'São Vicente',
    estado: 'SP',
    concluida: false,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 0,
    pagoStatus: 'NAO',
    observacoes: 'Data a confirmar',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Felipe Rossi',
    clienteDoc: '111.222.333-57',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-09-11',
    horario: '14:00',
    horarioTermino: '15:00',
    duracao: 1,
    local: 'BK HORTOLANDIA',
    cidade: 'Hortolândia',
    estado: 'SP',
    concluida: false,
    parceria: 'Buffet Parceiro',
    valorCobrado: 800,
    valorPago: 0,
    pagoStatus: 'NAO',
    observacoes: 'Data a confirmar',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Giovanna Antonelli',
    clienteDoc: '111.222.333-58',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-08-28',
    horario: '14:00',
    horarioTermino: '15:00',
    duracao: 1,
    local: 'BK SANTA CASA LITORAL',
    cidade: 'Santos',
    estado: 'SP',
    concluida: true,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 0,
    pagoStatus: 'NAO',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Giovanna Antonelli',
    clienteDoc: '111.222.333-59',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-09-12',
    horario: '14:00',
    horarioTermino: '15:00',
    duracao: 1,
    local: 'BK BARAO DE ITAPETININGA',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: false,
    parceria: 'Buffet Parceiro',
    valorCobrado: 650,
    valorPago: 0,
    pagoStatus: 'NAO',
    observacoes: 'Data a confirmar',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Giovanna Antonelli',
    clienteDoc: '111.222.333-60',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-09-13',
    horario: '14:00',
    horarioTermino: '15:00',
    duracao: 1,
    local: 'BK AV DOM PEDRO GUARUJA',
    cidade: 'Guarujá',
    estado: 'SP',
    concluida: false,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 0,
    pagoStatus: 'NAO',
    observacoes: 'Data a confirmar',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Giovanna Antonelli',
    clienteDoc: '111.222.333-61',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-09-14',
    horario: '14:00',
    horarioTermino: '15:00',
    duracao: 1,
    local: 'BK EXTRA RICARDO JAFET',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: false,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 0,
    pagoStatus: 'NAO',
    observacoes: 'Data a confirmar',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Giovanna Antonelli',
    clienteDoc: '111.222.333-62',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-09-15',
    horario: '14:00',
    horarioTermino: '15:00',
    duracao: 1,
    local: 'BK AV RICARDO JAFET',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: false,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 0,
    pagoStatus: 'NAO',
    observacoes: 'Data a confirmar',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Giovanna Antonelli',
    clienteDoc: '111.222.333-63',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-09-16',
    horario: '14:00',
    horarioTermino: '15:00',
    duracao: 1,
    local: 'BK SHOP CANINDE',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: false,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 0,
    pagoStatus: 'NAO',
    observacoes: 'Data a confirmar',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Giovanna Antonelli',
    clienteDoc: '111.222.333-64',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-09-17',
    horario: '14:00',
    horarioTermino: '15:00',
    duracao: 1,
    local: 'BK RADIAL LESTE',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: false,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 0,
    pagoStatus: 'NAO',
    observacoes: 'Data a confirmar',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Giovanna Antonelli',
    clienteDoc: '111.222.333-65',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-09-18',
    horario: '14:00',
    horarioTermino: '15:00',
    duracao: 1,
    local: 'BK METRO SANTA CRUZ',
    cidade: 'São Paulo',
    estado: 'SP',
    concluida: false,
    parceria: 'Buffet Parceiro',
    valorCobrado: 550,
    valorPago: 0,
    pagoStatus: 'NAO',
    observacoes: 'Data a confirmar',
  },
  {
    festaTipo: 'CORPORATIVO',
    clienteNome: 'Giovanna Antonelli',
    clienteDoc: '111.222.333-66',
    atracao: 'Robo Nextrom',
    efeitos: 'Cilindro e gerb',
    data: '2026-09-19',
    horario: '14:00',
    horarioTermino: '15:00',
    duracao: 1,
    local: 'BK LITORAL PLAZA - PRAIA GRANDE',
    cidade: 'Praia Grande',
    estado: 'SP',
    concluida: false,
    parceria: 'Buffet Parceiro',
    valorCobrado: 1000,
    valorPago: 0,
    pagoStatus: 'NAO',
    observacoes: 'Data a confirmar',
  },
];

/**
 * Função principal que popula todos os clientes, eventos e lançamentos financeiros
 */
export function seedSheetEvents(): { clientsCount: number; eventsCount: number } {
  // 1. Garante que as atrações necessárias existam
  const getOrInsertAttraction = (nome: string, categoria: 'ROBO_LED' | 'PERSONAGEM_VIVO' | 'OUTRO', valorBase: number) => {
    let row = db.prepare('SELECT id FROM atracoes WHERE nome LIKE ?').get(`%${nome}%`) as { id: number } | undefined;
    if (!row) {
      const res = db.prepare(`
        INSERT INTO atracoes (nome, categoria, descricao, valor_base, ativo)
        VALUES (?, ?, ?, ?, 1)
      `).run(nome, categoria, `${nome} oficial para apresentações`, valorBase);
      return Number(res.lastInsertRowid);
    }
    return row.id;
  };

  const roboNextromId = getOrInsertAttraction('Robô Nextrom (LED & Efeitos)', 'ROBO_LED', 550);
  const laCasaId = getOrInsertAttraction('La Casa de Papel', 'PERSONAGEM_VIVO', 400);

  // 2. Helper de Cliente
  const getOrInsertClient = (nome: string, doc?: string, tel?: string, email?: string, endereco?: string) => {
    let row = db.prepare("SELECT id, cpf FROM clientes WHERE nome = ? OR (cpf = ? AND cpf != '')").get(nome, doc || '') as { id: number; cpf: string } | undefined;
    if (!row) {
      const fakeDoc = doc || `000.${Math.floor(Math.random() * 899 + 100)}.${Math.floor(Math.random() * 899 + 100)}-00`;
      const end = endereco || 'São Paulo - SP';
      const res = db.prepare(`
        INSERT INTO clientes (nome, cpf, endereco, telefone, email)
        VALUES (?, ?, ?, ?, ?)
      `).run(nome, fakeDoc, end, tel || '', email || '');
      return Number(res.lastInsertRowid);
    }
    return row.id;
  };

  let totalEvents = 0;
  const clientIdsSet = new Set<number>();

  for (const item of SHEET_EVENTS_DATA) {
    const clientId = getOrInsertClient(item.clienteNome, item.clienteDoc, item.clienteTel, item.clienteEmail, item.clienteEnd);
    clientIdsSet.add(clientId);

    // Determina status
    let status = 'AGENDADO';
    if (item.cancelado) {
      status = 'CANCELADO';
    } else if (item.concluida) {
      status = 'REALIZADO';
    } else if (item.pagoStatus === 'PARCIAL' || item.pagoStatus === 'SIM') {
      status = 'CONFIRMADO';
    }

    // Monta observações com efeitos e parceria
    const obsArr: string[] = [];
    if (item.parceria) obsArr.push(`Parceria: ${item.parceria}`);
    if (item.efeitos && item.efeitos !== 'N') obsArr.push(`Efeitos: ${item.efeitos}`);
    if (item.observacoes) obsArr.push(item.observacoes);
    const observacoes = obsArr.join(' | ');

    // Verifica se evento já existe para evitar duplicata (mesmo cliente, data e local)
    const existingEv = db.prepare(`
      SELECT id FROM eventos WHERE cliente_id = ? AND data = ? AND endereco = ?
    `).get(clientId, item.data, item.local) as { id: number } | undefined;

    let eventId: number;
    if (!existingEv) {
      const res = db.prepare(`
        INSERT INTO eventos (
          cliente_id, nome_evento, tipo_evento, data, horario, horario_termino,
          endereco, cidade, estado, duracao, status, valor_total, observacoes
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `).run(
        clientId,
        `${item.atracao} - ${item.clienteNome}`,
        item.festaTipo || 'CORPORATIVO',
        item.data,
        item.horario,
        item.horarioTermino || '22:00',
        item.local,
        item.cidade || 'São Paulo',
        item.estado || 'SP',
        item.duracao || 1,
        status,
        item.valorCobrado,
        observacoes
      );
      eventId = Number(res.lastInsertRowid);
      totalEvents++;

      // Vincula atração
      db.prepare(`
        INSERT INTO evento_atracoes (evento_id, atracao_id, quantidade, valor_unitario)
        VALUES (?, ?, 1, ?)
      `).run(eventId, roboNextromId, item.valorCobrado);

      if (item.atracao.toLowerCase().includes('la casa')) {
        db.prepare(`
          INSERT INTO evento_atracoes (evento_id, atracao_id, quantidade, valor_unitario)
          VALUES (?, ?, 1, 0)
        `).run(eventId, laCasaId);
      }

      // Lançamentos Financeiros
      if (item.pagoStatus === 'SIM' || (item.concluida && !item.pagoStatus)) {
        // Totalmente pago
        db.prepare(`
          INSERT INTO lancamentos_financeiros (
            evento_id, cliente_id, descricao, tipo_parcela, valor, data_vencimento, data_pagamento, status, forma_pagamento
          )
          VALUES (?, ?, ?, 'AVULSO', ?, ?, ?, 'PAGO', 'PIX')
        `).run(
          eventId,
          clientId,
          `Pagamento Total - ${item.atracao} em ${item.local}`,
          item.valorCobrado,
          item.data,
          item.data
        );
      } else if (item.pagoStatus === 'PARCIAL') {
        // Sinal pago e restante pendente
        const pago = item.valorPago || 0;
        const restante = (item.valorCobrado || 0) - pago;

        if (pago > 0) {
          db.prepare(`
            INSERT INTO lancamentos_financeiros (
              evento_id, cliente_id, descricao, tipo_parcela, valor, data_vencimento, data_pagamento, status, forma_pagamento
            )
            VALUES (?, ?, ?, 'ENTRADA', ?, ?, ?, 'PAGO', 'PIX')
          `).run(
            eventId,
            clientId,
            `Sinal (40%) - ${item.atracao} (${item.local})`,
            pago,
            item.data,
            item.data
          );
        }

        if (restante > 0) {
          db.prepare(`
            INSERT INTO lancamentos_financeiros (
              evento_id, cliente_id, descricao, tipo_parcela, valor, data_vencimento, status
            )
            VALUES (?, ?, ?, 'RESTANTE', ?, ?, 'PENDENTE')
          `).run(
            eventId,
            clientId,
            `Saldo Restante (60%) - ${item.atracao} (${item.local})`,
            restante,
            item.data
          );
        }
      } else if (item.pagoStatus === 'NAO') {
        // Não pago / Pendente
        db.prepare(`
          INSERT INTO lancamentos_financeiros (
            evento_id, cliente_id, descricao, tipo_parcela, valor, data_vencimento, status
          )
          VALUES (?, ?, ?, 'AVULSO', ?, ?, 'PENDENTE')
        `).run(
          eventId,
          clientId,
          `A Cobrar - ${item.atracao} (${item.local})`,
          item.valorCobrado,
          item.data
        );
      }
    }
  }

  return {
    clientsCount: clientIdsSet.size,
    eventsCount: totalEvents,
  };
}
